---
# travis-ci config for pipdeptree

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install: make test-env
install:
  - pip install pip>=8.0.2
  - pip install .
script: py.test -v
after_script: make clean clean-env
sudo: false
